### ISSUE TITLE
PHP fatal error: Uncaught ArgumentCountError

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-plugin#1162]
**Describe the bug**
With Newspack image credits plugin codebase integrated in this plugin, https://github.com/Automattic/newspack-image-credits/issues/6 has started appearing with this plugin also

**To Reproduce**
1. Use latest version of plugin
2. View error.log
3. See error as below

```
2021/09/27 16:19:19 [error] 42837#42837: *11156 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Newspack\Newspack_Image_Credits::add_credit_to_attachment_excerpts(), 1 passed in /wp-includes/class-wp-hook.php on line 303 and exactly 2 expected in /wp-content/plugins/newspack-plugin/includes/class-newspack-image-credits.php:197
Stack trace:
#0 /wp-includes/class-wp-hook.php(303): Newspack\Newspack_Image_Credits::add_credit_to_attachment_excerpts()
#1 /wp-includes/plugin.php(189): WP_Hook->apply_filters()
#2 /wp-content/plugins/fb-instant-articles/class-instant-articles-post.php(209): apply_filters()
#3 /wp-content/plugins/fb-instant-articles/feed-template.php(46): Instant_Articles_Post->get_the_excerpt()
#4 /wp-content/plugins/fb-instant-articles/facebook-instant-articles.php(132): include('/sitename...')
#5 /var" while reading response header from upstream, client: XXXX, server: sitename.com, request: "GET /feed/instant-articles HTTP/2.0", upstream: "fastcgi://unix:/xxxx.sock:", host: "www.sitename.com"
```

**Expected behavior**
Not sure if this has to be handled in Facebook instant articles plugin or here, but ultimately no error should occur in logs.

**Comment by dkoo** [comment]
@yogeshbeniwal Thanks for the report! This error you're seeing is indeed originating in the FB Instant Articles plugin. I opened a PR in that repo to address it here: https://github.com/Automattic/facebook-instant-articles-wp/pull/1082
