### ISSUE TITLE
Uncaught Error: Class 'WC_Name_Your_Price_Helpers' not found

### ISSUE THREAD

**Issue by gusaus** [Automattic/newspack-plugin#2361]
**Describe the bug**
We recently switched the Reader Revenue Platform from Newspack to Stripe on a customer site. After disabling WooCommerce Name Your Price and WooCommerce Subscriptions, we noticed the following error on the cart page.

<img width="703" alt="Cart - Angel City Jazz 2023-03-20 14-52-56" src="https://user-images.githubusercontent.com/113996/226473903-b970a19f-d88a-4ad2-83b6-9fd97b0c5e9e.png">

This is how it reads in the WooCommerce Logs - 

`Fatal error: Uncaught Error: Class 'WC_Name_Your_Price_Helpers' not found in /code/wp-content/plugins/newspack-plugin/includes/class-donations.php:243 Stack trace: #0 /code/wp-content/plugins/newspack-plugin/includes/class-donations.php(963): Newspack\Donations::get_donation_product_child_products_ids() #1 /code/wp-includes/class-wp-hook.php(308): Newspack\Donations::handle_cart('') #2 /code/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #3 /code/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #4 /code/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-cart.php(91): do_action('woocommerce_che...') #5 /code/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(72): WC_Shortcode_Cart::output(Array) #6 /code/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(85): WC_Shortcodes::shortcode_wrapper(Array) #7 /code/wp-includes/shortcodes.php(355): WC_Shortcodes::cart('', '', 'woocommerce_car...') #8 [internal function]: do_shortcode_tag(Array) #9 /code/wp- in /code/wp-content/plugins/newspack-plugin/includes/class-donations.php on line 243 `

Considering the error went away after re-enabling the plugins, we're assuming there's some sort of leftover dependency?

Not surprisingly we could 'not' replicate on a clean install where Stripe was the Reader Revenue platform from the start (and did not install/enable Subscriptions and Name Your Price.

**Comment by davisshaver** [comment]
This seems to still be an issue. I added some additional checks in the init function.

```
		if (
			! is_admin() &&
			class_exists( 'WC_Name_Your_Price_Helpers' ) &&
			function_exists( 'WC' ) &&
			class_exists( 'WC_Subscriptions_Product' )
		) {
```

**Comment by gusaus** [comment]
I'm assuming this isn't an issue on the Newspack hosted service but most (all?) self hosted environments are affected, right?
